name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup conda
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: env.yml
      - name: Install kerchunk
        shell: bash -l {0}
        run: |
          pip install kerchunk
          pip install ipfsspec
      - name: Test with python
        shell: bash -l {0}
        run: |
          uname -a
          which python
          ls -lh ./data/ATL08*
          python ATL08.py
          ls -lh ATL08.json
          which nc-config
          nc-config --has-nczarr
          echo $PWD
          ncdump "file:///$PWD/ATL08.json#mode=nczarr"
          