name: Hyrax on Ubuntu-20.04

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ubuntu-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install Packages
        run: sudo apt-get --yes install libxml2-dev uuid-dev libcurl4-openssl-dev libcppunit-dev libfl-dev gcovr libtirpc-common libtirpc-dev libtirpc3
      - name: Build Hyrax
        run: |
          ./ci.sh
          pwd
          ls
          
